server:
  port: 80
  servlet:
    context-path: /Kostmetolog
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/diploma
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  main:
    allow-circular-references: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 908417680536-vqgqtur5qn9g9ajitu2ho1ut66h7fsqs.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 1065065327239672
            client-secret: 36b56b7e6d6540eb7a40d538f8d99c05
            scope:
            - email
            - public_profile
